width = float(input('width'))
long = float(input('long'))
heigth = float(input("heigth"))
D_fout = (width)*(long)
D_side = (width)*(heigth)
D_top = (heigth)*(long)
Gallon = round (((D_fout*2)+(D_side*2)+(D_top*2))/5)
print  ('ซื้อ',Gallon,'Gallon')
print  ('ซื้อ'+str(Gallon)+'Gallon')
print  (f'ซื้อ{Gallon}')
print  ('ซื้อ{}'.format(Gallon))